### ISSUE TITLE
make the under construction site not look like a wii texture

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [ForeverPyrite/ForeverPyrite.github.io#8]
seriously that's some wii era texture resolution

**Comment by ForeverPyrite** [comment]
> seriously that's some wii era texture resolution

I don't know who you are, BUUUUUTTTTT I can't update the site until I get a decent laptop so it's not even arranged. I was halfway into a big change. Also, it was actually intentional. Someone suggested an implantation into the CSS for it. They thought it would sharpen it, instead it pixilated it. Once I can update it again, I will prolly fix it lol.

Thanks though, never realized I didn't take out the N64 graphics.

**Comment by ForeverPyrite** [comment]
Alright here is news:

The banner just won't work like a normal CSS block, and I can't use a decent code interface because ***PotatoPC™️*** as you already know. So unless you put in a pull request, I will fix it when I can use *Visual Studio Code*.

Otherwise, I did delete the pixilated bit, and I added an extra little link because I am bored AF until I get this new computer. It's like 4AM right now. 

[Here is the barely better looking banner page with that link](https://foreverpyrite.github.io/about/site-construction)

The link leads to a wallpaper I spent a long time making. Anyways, if you want to say anything further, re-open the issue someone or just hit me up on Discord.
